### ISSUE TITLE
公告

### ISSUE THREAD

**Issue by MYXXTS** [heyblog/V2#100]
是否需要一个第三方程序来进行相关公告的发布
目前有三种方案：
1. 博客：官方博客，发布项目的一些公告，可以有他人参与讨论，互动性较低
2. 论坛：站长论坛，可以发布项目的一些公告，也可以让站长进行入驻，讨论和交流，互动性最高
3. 不使用任何程序，在项目程序内内置一个公告发布的地方，无互动性
但是我们后续还需要制作站长平台，所以需要各位考虑一下

**Comment by linlinzzo** [comment]
这个仓库加个 discussion？自建一个讨论区？如果你有精力来运营的话是可以。（好像不能在国内办论坛······）             
官方博客我感觉没必要，公告没什么内容，技术组的文章也发在他们自己的博客上（例如 https://www.ohyee.cc/post/note_cache_variables_for_hotload ）。

**Comment by OhYee** [comment]
项目公告感觉可以写死在页面上，或者放数据库里。

博客导航本身有啥功能对于大多数用户来说可能并不是很关心

讨论、交流最好还是通过即时通讯工具（qq 群、微信群、tg 群），论坛活跃性很难保证

文章可以考虑和公告一样，做个外链。不过这玩意本质上类似于 ”优秀文章推荐“（对标优秀博客推荐），也不一定局限于我们自己的

**Comment by MYXXTS** [comment]
那就写个项目公告功能出来吧，然后发布者得写死，局限到某几个人上

**Comment by linlinzzo** [comment]
zhblogs 目前似乎有一个叫 key admin 的东西。

**Comment by linlinzzo** [comment]
@OhYee 项目公告功能，权限需写死。
