### ISSUE TITLE
组内讨论-博客统计升级

### ISSUE THREAD

**Issue by linlinzzo** [heyblog/V2#101]
存储每周六的最终统计结果，方便往后查看调查结果变化，比如五年内博客架构的变化情况。

调查博客的 https 情况、更新频率等。

**Comment by OhYee** [comment]
需要确定下这个统计是只需要这个结果，还是可能会有其他需求。

涉及到这个数据怎么存储

**Comment by linlinzzo** [comment]
> 需要确定下这个统计是只需要这个结果，还是可能会有其他需求。

只需要显示结果。类似 https://myssl.com/https_reports.html ，可以查看变化趋势和历月的数据图表。

**Comment by linlinzzo** [comment]
具体需求之后用Echart表述。
