### ISSUE TITLE
组内讨论-[统计信息 todo]

### ISSUE THREAD

**Issue by linlinzzo** [heyblog/V2#102]
- [ ] 检查博客网站的 https 情况，并输出到 status 字段
- [ ] 将代码迁移到 Github Action 定期更新数据（之后可能不用 json 了···）

#101

**Comment by linlinzzo** [comment]
原先第二条没必要了，已经删掉了。

**Comment by OhYee** [comment]
这个数据需要存到数据库里存储下，需要确定下格式和接口

**Comment by linlinzzo** [comment]
@zkeq 
SEE https://github.com/zh-blogs/blog-daohang/blob/main/utils/api.ts#L109-L132

token 从 cookie 里面找，两个可能的接口在线地址：

https://zhblogs.ohyee.cc/api/blogs  GET
https://zhblogs.ohyee.cc/api/blog  POST
