### ISSUE TITLE
用于与 saveweb 互联

### ISSUE THREAD

**Issue by yzqzss** [heyblog/V2#105]

**Comment by yzqzss** [comment]
https://github.com/saveweb/doing/issues/232

idx:1314 | vzchnのBlog

@zh-blogs/list-team

**Comment by linlinzzo** [comment]
ssl证书不可信：

- https://blog.dugulingping.com/

https://ngzhio.github.io/ 404

**Comment by yzqzss** [comment]
@yeyuxingchen
您博客SSL证书到期了。

**Comment by linlinzzo** [comment]
网站出现问题的统一放这

ssl:

- [ ] https://blog.mayandev.top/ 
- [ ] https://jdqiong.cn/
- [ ] https://yazhen.me/

DNS_PROBE_FINISHED_NXDOMAIN:

- [ ] https://aboke.net/
- [ ] https://bninecoding.com/
- [ ] https://blog.maolu.one/
- [ ] https://dbarobin.com/
- [ ] https://www.aceact.com/
- [ ] https://gyl-coder.top/
- [ ] https://www.yinwang.org/

内容为空（403无法访问）：

- [ ] https://peon.top/
- [ ] http://qingchun.org/
- [ ] http://www.0lbo.cn/
- [ ] https://masily365.github.io/
- [ ] http://louishan.com/
- [ ] https://www.ad-s.cn/
- [ ] https://www.jinbo123.com/

**Comment by linlinzzo** [comment]
关于 saveweb 与 zh-blogs 合作的一些问题：
（在此处，rss-list 和 saveweb 不做区分）

1. 如何才能更好地实现同步？能否合并实现同源？（比如 saveweb 那里开个 API，直接用脚本同步等等）
2. 如何在“博客存档”方面合作？（由 zh-blogs 向 saveweb 推送文章，或 saveweb 添加 zh-blogs 收集到的 RSS）
3. zh-blogs 在合作中需要提供什么？能提供什么？
4. saveweb 在合作中需要提供什么？又能提供什么？

**Comment by yzqzss** [comment]
> 关于 saveweb 与 zh-blogs 合作的一些问题： （在此处，rss-list 和 saveweb 不做区分）

讨论这些花里胡哨的干嘛，干就完事儿了！

**Comment by yzqzss** [comment]
https://github.com/saveweb/doing/issues/221#issuecomment-1192103076

**Comment by linlinzzo** [comment]
https://ii.do/ ： cdn.ii.do ssl证书过期，导致样式掉了

**Comment by linlinzzo** [comment]
https://yupei-du.github.io/ 404

**Comment by linlinzzo** [comment]
https://www.zhenhetang.com/ ssl证书失效

**Comment by linlinzzo** [comment]
https://www.djttfor.cn/ 证书过期

**Comment by jsun969** [comment]
@yzqzss 能否放到你们的仓库
