### ISSUE TITLE
组内讨论-[精选博客采用推荐制]

### ISSUE THREAD

**Issue by linlinzzo** [heyblog/V2#107]
请描述内容内容，并 @ 相关成员

这个东西的目的是向用户推荐**优秀**的博客。

- 精选博客应该如何产生？
- 如果采用推荐制，那谁可以推荐？需要多少人推荐？
- 技术类博客要参与推荐吗？

**Comment by MYXXTS** [comment]
精选博客需要一个既定的标准，但是这个标准还在界定
可以推荐，任何人，但是需要在推荐的时候附上理由，在推荐之后由人员在既定标准值上进行审核
参与的博客推荐除了不能是收集资源类的那种网站之外其余网站都可以

**Comment by MYXXTS** [comment]
关于既定的标准，目前能想到的是：
1. 博客内容原创居多，至少占有全部文章的80%以上。
2. 博客运行不少于3年
3. 博客文章不少于50篇
