### ISSUE TITLE
组内讨论-[博文存档]

### ISSUE THREAD

**Issue by linlinzzo** [heyblog/V2#110]
请描述内容内容，并 @ 相关成员

文档地址：
[blog-archive](/zh-blogs/blog-archive/)
[存档代码的接口文档](https://zh-blogs.icodeq.com/docs)

看一下谁的服务器能部署。

**Comment by OhYee** [comment]
没部署文档么

**Comment by OhYee** [comment]
@linlinzzo @zkeq 
写个部署文档或者做成 docker 镜像吧

我看配置好多都是写死的，最好分成配置文件，不然换个环境部署还得修改代码本身

**Comment by linlinzzo** [comment]
@OhYee   
zkeq 现在没有精力来整 python 了。最坏的打算就是看组里其他人能不能接。

**Comment by zkeq** [comment]
我现在过来学前端了...

https://xiedaimala.com/courses/16644d89-6b17-4c2f-ac15-dabb994b7696/random/089657b69c?#/common

部署文档就是正常的

运行需求：
- `python3+`
- `redis`

```bash
pip install -r requirements.txt
python main.py
```

启动前若机器 `6379` 端口有 `redis`，则注释这两行即可（启动redis的）
https://github.com/zh-blogs/blog-archive/blob/ce287872b6646c03caf9310859ff917a57506cd0/main.py#L5
https://github.com/zh-blogs/blog-archive/blob/ce287872b6646c03caf9310859ff917a57506cd0/main.py#L138

这两行写死是因为这是当时基于 `replit` 的 `demo` 开发的...确实应该把这些分离出来
