### ISSUE TITLE
组内讨论-[关于利用好标签的讨论]

### ISSUE THREAD

**Issue by linlinzzo** [heyblog/V2#114]
博客标签是对博客内容的概括性描述。该如何更好地利用好博客标签？我个人有以下思考。

1. 可以帮助找到感兴趣的博客（开通博客邮件推荐功能，定期用邮件推送标签内的博客。开通“看看与该博客类似的博客”等功能。之前让一些博客传了`from`参数，要不要用起来？）
2. 博客标签同时还将博主分了类，这个……

**Comment by MYXXTS** [comment]
先完善系统

**Comment by jsun969** [comment]
v3会有新的标签系统
