### ISSUE TITLE
网站无法显示？

### ISSUE THREAD

**Issue by fengwyue** [heyblog/V2#127]
网站只能显示主页的框架，需要数据处理的地方全部无法显示。已经尝试更换浏览器和网络。
如图：
![](https://upload.cc/i1/2023/01/31/RVdGJH.png
)

**Comment by linlinzzo** [comment]
补充：“博客列表”“数据图表”tab无法正常点击，“博客登记”页面功能异常。

**Comment by linlinzzo** [comment]
![image](https://user-images.githubusercontent.com/79007796/215625291-62f52702-0028-4ff9-8061-db5d8410f06c.png)

一些 js 和 css 文件访问出现 514 错误。接口可以正常访问，但网络日志里面没有接口的请求。

**Comment by OhYee** [comment]
安全防护限流值设置太低了，部分正常请求被限流。
调高了单 ip QPS 限制
