### ISSUE TITLE
Bug反馈-主页 HTML 代码有误

### ISSUE THREAD

**Issue by villivateur** [heyblog/V2#19]
请仔细描述这个漏洞：
87行少一个 </div> 标签
![image](https://user-images.githubusercontent.com/30222160/159890748-c6dc454c-9585-45f3-bde9-0a50bf9d80f6.png)

**Comment by OhYee** [comment]
在 commit https://github.com/linlinzzo/blog-daohang/commit/acca35cc1754e4af39860ba16f317839e9db4bfe 已修复

重新部署了下并刷新了 CDN 缓存，可以重新访问试下

https://zhblogs.ohyee.cc/
