### ISSUE TITLE
Bug反馈-[列表加载失败]

### ISSUE THREAD

**Issue by linlinzzo** [heyblog/V2#22]
请仔细描述这个漏洞（浏览器、复现方式等我们需要的信息）：
浏览器为华为自带浏览器，先前可正常加载列表。现多次刷新均无法加载，截图如下:
![Screenshot_20220326-172344](https://user-images.githubusercontent.com/79007796/160233375-55733393-9c96-46d8-b321-7856500f5c9f.jpg)
![Screenshot_20220326-172349](https://user-images.githubusercontent.com/79007796/160233381-da145cc8-23a1-47f5-ba59-4dc5e6928420.jpg)
![Screenshot_20220326-172354](https://user-images.githubusercontent.com/79007796/160233388-812f878a-8bc1-4a5a-aa39-c49bdafa724f.jpg)
今日16时10分，收到来信，同样指出列表不可用。
![Screenshot_20220326-172816](https://user-images.githubusercontent.com/79007796/160233494-4660c44e-0edb-4ac6-91a6-de71eb490a90.jpg)

**Comment by OhYee** [comment]
JSON 文件最后有个逗号，json解析失败
![image](https://user-images.githubusercontent.com/13498329/160234436-7629055a-aa77-413f-8310-762e9326a476.png)

**Comment by linlinzzo** [comment]
目前功能恢复正常。
