### ISSUE TITLE
随机博客推荐-优化建议

### ISSUE THREAD

**Issue by linlinzzo** [heyblog/V2#23]
1. 再来十个按钮可以换用以下bootstrap图标：
  [arrow-clockwise](https://icons.bootcss.com/icons/arrow-clockwise/)
  [arrow-counterclockwise](https://icons.bootcss.com/icons/arrow-counterclockwise/)
  [arrow-repeat](https://icons.bootcss.com/icons/arrow-repeat/)
2. 在表格中删除状态、标签和博客描述。
3. 在加载随机博客推荐时，没必要加载博客列表中的功能，等到用户点击博客列表在加载对应的代码也行。

**Comment by OhYee** [comment]
新版本 fix
