### ISSUE TITLE
申请删除网站-[444]

### ISSUE THREAD

**Issue by iduzui** [heyblog/V2#24]
网站序号：444
网站需要修改的信息：请删除本人的博客及链接：雨落泪尽，https://couqiao.net

**Comment by linlinzzo** [comment]
我们需要您通过以下任一方法验证`雨落泪尽`的博客站长身份：
1. 在网站首页的头部中插入`<meta name="zhblogs-verification" content="iduzui" />`
2. 添加 TXT 记录，主机名为`zhblogs-verification`，值为`iduzui`。

完成添加后，请向我们描述您申请删除网站的原因。
在网站删除后，其修改将在次日同步，验证信息可以删除。

**Comment by yzqzss** [comment]
理由就不需要吧，毕竟是主动收录的。

**Comment by linlinzzo** [comment]
> 理由就不需要吧，毕竟是主动收录的。

我认为需要。尽管有时候站长可以选择不回答，退出理由有时是问题解决的突破口（因为我猜测大部分站长并不会主动要求退出，一定是有些设计惹到了他们）。
![站长截图](https://user-images.githubusercontent.com/79007796/160504109-2bc8bd9e-d83b-45ee-b4d9-458f0afa36d7.PNG)
