### ISSUE TITLE
申请添加网站

### ISSUE THREAD

**Issue by asforest** [heyblog/V2#27]
网站网址（多个请换行）： https://aprilforest.cn

看到大佬搞这个项目，前来支持一下哈 😄 （话说不需要写描述和标签之类的嘛？）

**Comment by linlinzzo** [comment]
标签由我们贴，描述我们会从网站上找，rss就稍微穷举一下。你要来帮忙吗？

**Comment by asforest** [comment]
没事我只是顺便问问哈，感觉可以让申请者自己填写，应该会比自己去找要快一些。
我太菜了，不会写React，实在是帮不上忙呀 😆 。

**Comment by linlinzzo** [comment]
> 没事我只是顺便问问哈，感觉可以让申请者自己填写，应该会比自己去找要快一些。 我太菜了，不会写React，实在是帮不上忙呀 😆 。

你其实也可以维护地址库······

**Comment by asforest** [comment]
是收到Issue之后在data.json添加对应的站点么

**Comment by linlinzzo** [comment]
> 是收到Issue之后在data.json添加对应的站点么

你可以给博客贴标签吗？

**Comment by asforest** [comment]
我刚看了下，好家伙，大概有450多个链接没有标签。要真的一个一个打标签效率也太低了吧。
个人建议最好能在申请信息里由站长提供。（当然也不是所有的链接都有申请issue）

**Comment by linlinzzo** [comment]
@asforest  有一些是我们根据上游库添加的。不要求效率，可以慢慢鸽。

**Comment by asforest** [comment]
这不是长久之计啊，都要手动打标签，很累的吧。
况且我平时也时间不是很多，后面越来越多的链接加到数据库里，会越积越多的。
个人建议用爬虫爬取或者不显示标签一栏比较好。

立项之初最好就要考虑到这个问题，用人力确实不是最优解

**Comment by linlinzzo** [comment]
> 这不是长久之计啊，都要手动打标签，很累的吧。 况且我平时也时间不是很多，后面越来越多的链接加到数据库里，会越积越多的。 个人建议用爬虫爬取或者不显示标签一栏比较好。 立项之初最好就要考虑到这个问题，用人力确实不是最优解

标签搜索功能已经被开发，现在其它关于标签的功能正在日程表。 
   之后可能会考虑由站长提交标签，但现在后台的开发还在进行，所以这个东西等明天讨论后台时提出。      
目前没有成熟的爬虫爬取的方案。         
还有另外一个小伙伴可以贴标签，之后再问一下他。
    如果你感觉可以的话，我要邀请你加入组织和我们的项目qq群。

**Comment by asforest** [comment]
感谢对我个人的认可，谢谢。但我目前还是决定持观望的态度。

个人的建议：可以使用爬虫爬取+人工审核的方式会稍微好一点。
可以由爬虫收集一些关键词，和一些站点截图。然后提交给人工，人工再从收集到的关键词里手动勾选1~5个标签。
人工审核过程尽量用web显示，优化布局。控制一个站点的审核时长尽量在1分钟以内。人工或许压力会小很多。

个人建议，不一定合适哈。

**Comment by linlinzzo** [comment]
> 个人的建议：可以使用爬虫爬取+人工审核的方式会稍微好一点。 可以由爬虫收集一些关键词，和一些站点截图。然后提交给人工，人工再从收集到的关键词里手动勾选1~5个标签。 人工审核过程尽量用web显示，优化布局。控制一个站点的审核时长尽量在1分钟以内。人工或许压力会小很多。
> 
> 个人建议，不一定合适哈。

![QQ图片20220331194355](https://user-images.githubusercontent.com/79007796/161047581-0c9b9abc-72f4-4e4b-8d72-d1db48f1d488.png)
很巧的是，我对于后台的期待也是这样。上面是之前在讨论时用的后台添加网站时的图片。我对于你持观望态度表示遗憾，我希望你能够加入我们并参与讨论（因为你的点子很棒）。       
我之前贴标签遇到技术性的专有名词时会看不懂，这使我在贴技术博客的标签时具有很大的劣势，将来对于爬虫也是一样。        
每次贴多少标签可以自己安排，请您再考虑一下。

**Comment by asforest** [comment]
抱歉，主要是年后我的事情突然就变多了，一直在忙准备工作方面的事情，实在抽不出太多多余的时间，连博客也是一个月更新一篇的样子。请理解！如果后面不那么忙了，我会回来继续支持这个项目的开发的。
