### ISSUE TITLE
请求协助

### ISSUE THREAD

**Issue by linlinzzo** [heyblog/V2#29]
@saveweb @yzqzss 
关键词：ssl失效, 协助联系
以下网站的 ssl 证书出现失效，请协助联系站长更新证书：
1. https://wanbk.net/
2. https://www.the5fire.com/
3. https://blog.fight365.cn/

以下网站未使用 ssl，可以建议使用 ssl：
https://zhblogs.ohyee.cc/?page=1&search=http%3A%2F%2F&tags=

**Comment by yzqzss** [comment]
收到，之后跟进。

**Comment by yzqzss** [comment]
对于没有使用 ssl 的博客，原则上不会去提醒博主使用 ssl 。
特别对于一些老博客来说，上 ssl 是不必要且成本高的，可能会有跨站导致外部资源无法加载的问题。
而且一些博主并不想干每几个月续签SSL的麻烦事，反正就一博客，没必要嘛。

**Comment by linlinzzo** [comment]
@yzqzss 我想询问一下有关站长的联系跟进情况。

**Comment by redish101** [comment]
@linlinzzo 1、2号网站的ssl证书已经正常，3号网站的ssl证书已经过期，我正在与站长去的联系
