### ISSUE TITLE
申请添加网站

### ISSUE THREAD

**Issue by imGmc** [heyblog/V2#31]
网站网址（多个请换行）：https://www.gmcllp.cn

**Comment by linlinzzo** [comment]
已修改，大约一小时后生效。
![截图20220330080921](https://user-images.githubusercontent.com/79007796/160725962-edafcbd1-0e75-4146-8697-910f6249179e.png)

**Comment by imGmc** [comment]
多谢！ :P

**Comment by linlinzzo** [comment]
> 多谢！ :P


能加入我们一起维护列表那就更好啦！
