### ISSUE TITLE
Bug反馈-[描述漏洞]

### ISSUE THREAD

**Issue by MYXXTS** [heyblog/V2#36]
请仔细描述这个漏洞（浏览器、复现方式等我们需要的信息）：
 Edge浏览器访问，无法正常加载
![Y45S%3H%R{HG请仔细描述这个漏洞（浏览器、复现方式等我们需要的信息）：
 Edge浏览器访问，无法正常加载
LS5_(VR 9](https://user-images.githubusercontent.com/51087760/162177542-01e5c564-349e-4e50-938b-b0b4b8490fbe.png)

**Comment by soxft** [comment]
fixed, tag 解析错误, 等待cdn同步
