### ISSUE TITLE
Bug反馈-[去重代码失效]

### ISSUE THREAD

**Issue by linlinzzo** [heyblog/V2#45]
请仔细描述这个漏洞（浏览器、复现方式等我们需要的信息）：
出现重复收录，然而没有提醒。目前该网站的重复收录已解决。
![QQ图1](https://user-images.githubusercontent.com/79007796/162551039-9f503a81-3093-43e2-a369-a5e4e5e522c9.png)

**Comment by OhYee** [comment]
新版本前端会 fix
