### ISSUE TITLE
新版本已知 bug

### ISSUE THREAD

**Issue by OhYee** [heyblog/V2#49]
- [ ] 换用新版本后端
- [ ] 跳转页面等待时间太久
- [ ] 跳转页面 logo 太大
- [ ] 跳转页面不显示 -1 秒
- [ ] 后台编辑切换站点后，底部站点预览不会更新到新站点

**Comment by linlinzzo** [comment]
moved to https://github.com/orgs/zh-blogs/projects/2/views/1
