### ISSUE TITLE
开设团队博客，用于发布公告和新功能

### ISSUE THREAD

**Issue by OhYee** [heyblog/V2#50]

**Comment by OhYee** [comment]
使用 discussions 或者 gh-pages 之类的静态部署就行吧
或者随着每次 release 版本的时候，在“关于”标签页（或者新建一个标签页）展示
这个功能应该不需要长篇大论吧
@linlinzzo

**Comment by linlinzzo** [comment]
gh-pages 好像就行。

**Comment by redish101** [comment]
用hexo吧，我这就落实

**Comment by OhYee** [comment]
@Redish101 
部署到哪，以及编辑怎么做（这个可能需要编辑的人不固定）

**Comment by zkeq** [comment]
如果用 hexo 的话, `vercel` 自动部署或许可以？

在 Github 仓库提交，vercel 会自动同步部署来着。

我的博客就是这样弄的
https://github.com/zkeq/Coding

**Comment by redish101** [comment]
@OhYee 我知道一个hexo manager，叫做[wexagonal](wexa.top)，可以用一下，方便管理
