### ISSUE TITLE
docker 镜像打包任务移至 github action

### ISSUE THREAD

**Issue by OhYee** [heyblog/V2#51]

**Comment by OhYee** [comment]
低优先级，可以参考下 dev.bash build 和 dev.bash push
如果这边自动化的话，可以只 push 到 github packages
@Mabbs

**Comment by Mabbs** [comment]
> 低优先级，可以参考下 dev.bash build 和 dev.bash push 如果这边自动化的话，可以只 push 到 github packages @Mabbs

那我写action的话是用那个脚本还是自己写？那个看起来里面没token应该执行的时候要输入东西的吧

**Comment by OhYee** [comment]
> 那我写action的话是用那个脚本还是自己写？那个看起来里面没token应该执行的时候要输入东西的吧

都行，看怎么方便点吧

目前 build 就是直接使用 docker build，只是脚本里自动识别了下 commit id，不过 github action 应该也有类似的版本逻辑
