### ISSUE TITLE
新增博客统计信息项并绘制图表

### ISSUE THREAD

**Issue by OhYee** [heyblog/V2#53]

**Comment by OhYee** [comment]
需要确认下展示的内容
@linlinzzo

**Comment by linlinzzo** [comment]
目前就先统计博客所使用的程序、博客网站状态、技术类生活类博客占比吧。

**Comment by OhYee** [comment]
博客状态现在谁在维护，这个状态数据存在哪

**Comment by linlinzzo** [comment]
> 博客状态现在谁在维护，这个状态数据存在哪

我认为状态还是像之前一样用爬虫抓取一下吧。

**Comment by OhYee** [comment]
> 我认为状态还是像之前一样用爬虫抓取一下吧。

这个现在是不是没人在做，数据怎么合并过来还需要对接下

**Comment by linlinzzo** [comment]
状态不准，不显示网站状态。

**Comment by OhYee** [comment]
to #63
