### ISSUE TITLE
开发浏览器插件，一键提交网站

### ISSUE THREAD

**Issue by OhYee** [heyblog/V2#61]
需要详细需求描述

可能需要考虑有没有相关技术栈的人员

@linlinzzo

**Comment by linlinzzo** [comment]
> ベ断桥烟雨ミ 20:49:22
> 就是我访问博客可以直接在浏览器上提交网站，自动补全信息。
> 
> ベ断桥烟雨ミ 20:49:34
> 不用再到网站上提交
> 
> 工藤新一 20:49:37
> 哦哦
> 
> 工藤新一 20:49:40
> 悬浮框类似于
> 
> ベ断桥烟雨ミ 20:49:46
> 是
> 
> ベ断桥烟雨ミ 20:59:55
> 我这种非专业人士看起来就是两个输入框和发请求
> 
> 工藤新一 21:00:19
> 我想 的是选中标题，简介啥的
> 
> 工藤新一 21:00:21
> 自动提交？
> 
> 工藤新一 21:00:36
> 都上插件了，还复制粘贴干啥（
> 
> ベ断桥烟雨ミ 21:00:40
> 抓取 title 吧
> 
> ベ断桥烟雨ミ 21:01:20
>  还是加个手动点击按钮吧
> 
> 工藤新一 21:01:38
> 嗯。就是手动点一下标题
> 
> 工藤新一 21:01:50
> 然后那边自动把标题填到框里
> 
> 工藤新一 21:01:52
> 之类的
> 
> ベ断桥烟雨ミ 21:02:06
> 机器抓取 head-title 的值可行？
> 
> 工藤新一 21:02:20
> 应该可行

**Comment by OhYee** [comment]
可以先考虑 Chromium 系

输入框要包含非必选字段么，按照之前列表组反馈，尽可能一步做完体验会比较好，可能需要考虑如果是管理员从插件提交后可以跳过审核

功能
- 获取网站标题、域名自动填写
- 其他字段填写
- 登录鉴权（需要在 zhblogs 登录后，获取 token，这里可能会有权限问题，需要看下能不能拿到 token）
- 绑定快捷键，触发添加
- 判断当前网站是否已存在（不存在可以弹提醒）

目前能想到得细节有这些，列表组可以从使用者角度考虑下
@zh-blogs/list-team 

这个排期估计会很靠后，如果有人有空，可以先认领下写一版 demo 
可能还需要考虑这个以个人账号还是团队账号提交

**Comment by MYXXTS** [comment]
觉得可以包含非必要字段，但是一定要折叠显示。
也就是说，必要字段是直接显示，然后再下方显示非必要字段，展开之后按需填写

**Comment by imjason** [comment]
我认为现在的当务之急是如何吸引站长使用加入，而不是添加大量网站，这样有一种感觉是在唱独角戏

**Comment by linlinzzo** [comment]
> 我认为现在的当务之急是如何吸引站长使用加入，而不是添加大量网站，这样有一种感觉是在唱独角戏

目前大部分网站是我们主动收录的，站长互动可能要等站长平台开发出来之后吧。
