### ISSUE TITLE
几个待定建议

### ISSUE THREAD

**Issue by MYXXTS** [heyblog/V2#63]
1. 删除几个字段：博客头像，联系邮箱，网站架构。
2. 修改隐藏栏为未审核栏。
3. 更改展示滑块为审核通过按钮。
4. 删除编辑栏中预览框。
5. 优化移动端界面，暂时出现移动端界面无法进入编辑的问题。

**Comment by soxft** [comment]
预览框 我认为没什么必要,  不如 直接加一个按钮 或超链接 直接打开网站 @OhYee

**Comment by MYXXTS** [comment]
在此陈述一下第一项的字段删除原因：
博客头像只是优化展示效果，目前作用不大，可以删除；
联系邮箱字段，如果对收录有疑问或者异议，可以通过项目组公共邮箱反馈，或者是到项目组博客留言，而且邮箱可能涉及博主隐私，不建议使用，再者，若一个个收集公开的博主邮箱也较为麻烦。

**Comment by OhYee** [comment]
> 预览框 我认为没什么必要, 不如 直接加一个按钮 或超链接 直接打开网站

两种形式都保留吧，可以加一个隐藏预览

**Comment by OhYee** [comment]
> 删除几个字段：博客头像，联系邮箱，网站架构。

cc @linlinzzo 


> 修改隐藏栏为未审核栏。
> 更改展示滑块为审核通过按钮。

随下一个更新修改

> 删除编辑栏中预览框。

个人建议默认隐藏（不渲染，不发请求），保留需要用到的场景

> 优化移动端界面，暂时出现移动端界面无法进入编辑的问题。

移动端不建议编辑，无法进入好像是手机跳转有问题，需要加重现描述

**Comment by redish101** [comment]
> > 删除几个字段：博客头像，联系邮箱，网站架构。
> 
> cc @linlinzzo
> 
> > 修改隐藏栏为未审核栏。
> > 更改展示滑块为审核通过按钮。
> 
> 随下一个更新修改
> 
> > 删除编辑栏中预览框。
> 
> 个人建议默认隐藏（不渲染，不发请求），保留需要用到的场景
> 
> > 优化移动端界面，暂时出现移动端界面无法进入编辑的问题。
> 
> 移动端不建议编辑，无法进入好像是手机跳转有问题，需要加重现描述

这就修改

**Comment by linlinzzo** [comment]
> 在此陈述一下第一项的字段删除原因： 博客头像只是优化展示效果，目前作用不大，可以删除； 联系邮箱字段，如果对收录有疑问或者异议，可以通过项目组公共邮箱反馈，或者是到项目组博客留言，而且邮箱可能涉及博主隐私，不建议使用，再者，若一个个收集公开的博主邮箱也较为麻烦。

个人建议删除联系邮箱字段。

**Comment by zkeq** [comment]
我也支持删除邮箱字段

如果把邮箱放在公开的 API 上..

万一被某些人群发垃圾邮件或者广告，应该会对博客主造成困扰。

**Comment by OhYee** [comment]
其他字段还要保留么

**Comment by linlinzzo** [comment]
删除联系邮箱字段，站点架构其实需要我们做标准化。博客头像目前没必要，而且之后添加到随机跳转可能会与页面冲突，还有防盗链。

**Comment by OhYee** [comment]
删除这两条？

![image](https://user-images.githubusercontent.com/13498329/167250742-33bb7513-549d-4d14-b82a-a43db80030a4.png)

**Comment by linlinzzo** [comment]
> 删除这两条？

是。

**Comment by MYXXTS** [comment]
那就目前删除一下博客头像和联系邮箱两条。
然后建议将展示更改为审核通过按钮。
隐藏栏更改为待审核栏。
隐藏网站渲染界面。
增加审核驳回，并在前台单独开辟一栏展示审核驳回博客。
更改一下后台博客信息顺序，顺序如下：
ID-博客名称-博客网址-博客描述-分类-加入时间-更新时间-RSS订阅地址-网站地图-网站架构
