### ISSUE TITLE
定时使用机器人在群里发备份文件，供成员保存

### ISSUE THREAD

**Issue by OhYee** [heyblog/V2#65]

**Comment by OhYee** [comment]
目前服务器上有一份备份
github 有定时任务备份
https://github.com/zh-blogs/zh-blog-database

有必要再添加群文件么

**Comment by soxft** [comment]
再保存一遍吧, action 今天push 提示rejected 但是我是force的. 不清楚原因,我去 排查一下

**Comment by linlinzzo** [comment]
> 目前服务器上有一份备份 github 有定时任务备份 https://github.com/zh-blogs/zh-blog-database
> 
> 有必要再添加群文件么

那既然这样就不用了。
