### ISSUE TITLE
组内讨论-登录相关问题

### ISSUE THREAD

**Issue by OhYee** [heyblog/V2#67]
本地测试 Github 登录出现弹下载框问题，需要确认下其他人有没有类似的情况

复现流程
- 点击 Github 登录
- 页面未刷新，弹出下载窗口（下载的内容是 manager.html 或 authority.html）
- 取消下载，手动刷新页面，登入到后台内

**Comment by Mabbs** [comment]
edge复现失败，你用的是什么浏览器

**Comment by OhYee** [comment]
> edge复现失败，你用的是什么浏览器

edge……，我看看是不是插件问题（不过我别的站点 github 登录没问题……）

**Comment by soxft** [comment]
暂时没遇到过 safari mac

**Comment by redish101** [comment]
edge 100 macos没有问题

**Comment by OhYee** [comment]
排查是 XDown 浏览器插件的问题
看上去不是登录接口的 Header 不符合规范
