### ISSUE TITLE
组内讨论 - 页面设计相关

### ISSUE THREAD

**Issue by soxft** [heyblog/V2#68]
1. #66 中 页脚增加博客, 5个lable 是否会引起不对称, 影响整体美观
2. join 页面 中, 填写内容过多, 且无任何"分组" 是否会引起 “填写疲劳”

**Comment by OhYee** [comment]
可以考虑折叠非必填字段？

**Comment by soxft** [comment]
可以试试 把必填的 和非必填的 隔开一些距离, 非必要的 可以默认隐藏, 用户点击`其他信息` 后 展开

**Comment by MYXXTS** [comment]
和 @linlinzzo 商议过之后认为目前的页面设计部分存在一些问题，我会尽快拿出一版网站逻辑的设计稿，交由开发组

**Comment by MYXXTS** [comment]
因项目整合，我不是很明白现在的项目到底有什么需求的，所以之前的设计稿已经作废。
请开发组和项目组成员告知需求，我可以重新设计。

**Comment by linlinzzo** [comment]
> 请开发组和项目组成员告知需求，我可以重新设计。

网站目前用来呈现列表具体内容、调查统计结果，帮助用户发现冷门优秀的博客（博客推荐功能、博客随机跳转），让用户获取博客目前的普遍状况（博客统计图表），加强博客之间的联系（友链朋友圈、中文博客搜索引擎，未来），Save即将消失的博客（博客存档，未来与saveweb合作），为站长搭建一个小众圈子（未命名）。

页面设计我个人感觉要清晰，尽快告诉用户：

1. 我们的项目是什么？
2. 我们的项目有什么特殊的地方？
3. 我们的目的是什么？

第三个问题，每个成员估计各自有自己的看法。在我看来，就是将这几百kB的数据文件利用到极致。

**Comment by MYXXTS** [comment]
好的，需求已明白
