### ISSUE TITLE
申请添加网站

### ISSUE THREAD

**Issue by liangchuxin** [heyblog/V2#7]
网站网址（多个请换行）：
https://blog.becomingcelia.com

**Comment by linlinzzo** [comment]
手机在中国移动的网络下打不开你的网站，明天用电脑试一下。抱歉，让你多等会。

**Comment by linlinzzo** [comment]
博客网站已添加。

**Comment by liangchuxin** [comment]
> 

这样子 😱 应该是 jsdelivr 太慢了

**Comment by liangchuxin** [comment]
> 

好的感谢！

**Comment by linlinzzo** [comment]
> > 
> 
> 这样子 😱 应该是 jsdelivr 太慢了

不是 cdn 的问题，是中国移动屏蔽了一些网站（包括我的）。

**Comment by linlinzzo** [comment]
> > 
> 
> 好的感谢！

不用谢！

**Comment by liangchuxin** [comment]
这样子 太离谱了
