### ISSUE TITLE
组内讨论-[网站推荐功能]

### ISSUE THREAD

**Issue by linlinzzo** [heyblog/V2#71]
请描述内容内容，并 @ 相关成员
@OhYee @MYXXTS 

开一个栏目推荐冷门优秀的博客，管理员可以在后台添加推荐的网站。

**Comment by OhYee** [comment]
要怎么展示，放在哪
怎么选择，填网站名、域名？
还是选择 id 关联到博客列表里？

**Comment by linlinzzo** [comment]
> 要怎么展示，放在哪 怎么选择，填网站名、域名？ 还是选择 id 关联到博客列表里？

1. 我的建议是和 关于、博客列表、随机博客推荐 放在一起。
2. 后台选择推荐的博客就关联 id 吧（不懂，你们技术组自己定）。

**Comment by MYXXTS** [comment]
可行，该建议和我正想做的一个项目相吻合

**Comment by OhYee** [comment]
> 我的建议是和 关于、博客列表、随机博客推荐 放在一起。
> 后台选择推荐的博客就关联 id 吧（不懂，你们技术组自己定）。

全都放，是做成类似谷歌广告那样么

**Comment by MYXXTS** [comment]
我觉得是两种实现方式：
1. 在后台审核选项添加一个字段，该字段为推荐字段，类似已有的是否显示，如果属于推荐字段内的。可以在首页开一个推荐栏目，然后在里面展示。
2. 手动写文章，在博客列表导航博客里面手动展示。

**Comment by linlinzzo** [comment]
这个是在 zhblogs.ohyee.cc 上显示的，我的想法是设立一个优秀冷门博客奖“朝闻道奖”，每周颁发一次，就这样定期给用户推荐博客。

**Comment by OhYee** [comment]
这个字段和原本的存储方式有点小冲突，需要先调整下存储字段

目前已经测试了 getBlogs 接口，后面还需要测试下修改的接口，没问题的话，会把这个以及 #72 加进去

**Comment by linlinzzo** [comment]
没能看到推荐博客在前端的展现。
