### ISSUE TITLE
组内讨论-添加 saveweb_id 字段

### ISSUE THREAD

**Issue by OhYee** [heyblog/V2#72]
https://github.com/saveweb/rss-list/issues/4#issuecomment-1133830237

**Comment by MYXXTS** [comment]
功能不冲突的情况下是可行的

**Comment by linlinzzo** [comment]
Agree. &nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zh-blogs/blog-daohang"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年5月22日(星期天) 下午5:55
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;[zh-blogs/blog-daohang] 组内讨论-添加 saveweb_id 字段 (Issue #72)





 
saveweb/rss-list#4 (comment)
