### ISSUE TITLE
组内讨论-[显示博客架构统计图表]

### ISSUE THREAD

**Issue by linlinzzo** [heyblog/V2#73]
请描述内容内容，并 @ 相关成员
如题。
根据 https://github.com/zh-blogs/blog-architecture 显示常见博客架构的图标、简介、官网。绘制博客架构统计图表。

**Comment by OhYee** [comment]
不在列表内的系统怎么选，算 其他 么

**Comment by linlinzzo** [comment]
是。

**Comment by linlinzzo** [comment]
@wibus-wee 
![3](https://user-images.githubusercontent.com/79007796/176814109-060f3c0d-5f8c-40ea-8034-6677a2a63a6c.PNG)
像 cloudflare 这样。

**Comment by penndu** [comment]
是打算自己分析呢？还是博主自行提交？

**Comment by linlinzzo** [comment]
> 是打算自己分析呢？还是博主自行提交？

1. 我们打算将数据公开出来，让人们看到目前的统计情况。
2. 极少一部分由博主自己填写，大部分由我们人工补全。
3. 如果有爬虫的话，首先可能有法律风险，其次一些站长会隐藏 generator 的元数据标签，这时可能要通过文件目录、其它标签进行分析，我这个门外人看着有点困难。

**Comment by wibus-wee** [comment]
若隐藏了元数据标签的话，我觉得就提交给人工处理好了

爬虫或许遵循robot.txt即可

**Comment by linlinzzo** [comment]
> 若隐藏了元数据标签的话，我觉得就提交给人工处理好了

目前是全部由人工添加，现在只要图表就好。

**Comment by linlinzzo** [comment]
@zkeq 之后可以用 Action + Python 每季度更新一次 arch 数据，出现异常交给人工。
另外，能否考虑统计更多的信息项？比如，大家通常几天更新一次、HTTPS在博客的普及情况等。

**Comment by zkeq** [comment]
> @zkeq 之后可以用 Action + Python 每季度更新一次 arch 数据，出现异常交给人工。 另外，能否考虑统计更多的信息项？比如，大家通常几天更新一次、HTTPS在博客的普及情况等。

我那代码操作起来有点...

就跑一次还好...搬到 `actions` 的话...应该还要改改
