### ISSUE TITLE
组内讨论-[友链朋友圈]

### ISSUE THREAD

**Issue by linlinzzo** [heyblog/V2#74]
请描述内容内容，并 @ 相关成员
友链接力，我们开发一个 js 放在中文博客网站（不是我们的官网，和网站推荐不一样）上，像谷歌广告那样，当用户访问中文博客时可以看到我们推送的随机博客。

----------------------------------------
OhYee 2022/5/8 12:44:38
最后这个你是想让别的站点加载这个js么

OhYee 2022/5/8 12:45:35
一方面是作为一个站长，一般是不应该加载第三方js的，存在安全隐患

OhYee 2022/5/8 12:45:59
另一方面是这个js加载之后，要把内容渲染到页面上，很难保证风格统一

OhYee 2022/5/8 12:46:12
基本上不可能做到好看

**Comment by Mabbs** [comment]
iframe可能更安全些，可以整两套风格的，就像wcg的小插件那样，或者是整成svg的也可以

**Comment by linlinzzo** [comment]
> iframe可能更安全些，可以整两套风格的，就像wcg的小插件那样，或者是整成svg的也可以

iframe可以添加一些自定义属性，尽量与博客的主题相适应。 @OhYee

**Comment by OhYee** [comment]
这个需求建议随机抽十个博客，分别设计下在边栏、底栏等位置为其设计一个展示效果

---

iframe 涉及父窗口和子窗口交互，需要需要 postMessage 同步数据才能有比较好的展示效果，需要博主开发能力
svg 在点击链接的兼容性上不确定能不能保证，另外 svg 缩放是等比缩放，可能没法保证展示效果

---

> 尽量与博客的主题相适应

这个没法实现，博客主题色、背景色不固定，很难有合适的风格

---

我对这个功能的实现呈悲观态度，毕竟谷歌广告做的也就那样，完全称不上好看

最靠谱的还是让用户调我们的接口获取列表，样式自己去适配
（另外这里还可能还需要考虑怎么涉及 cdn 缓存，目前这些接口为了保证每次刷新都不同，是不走 CDN 的，如果使用这个服务的博客过多，可能需要考虑下怎么做缓冲）

**Comment by yzqzss** [comment]
友链朋友圈这个名字，和 https://github.com/Rock-Candy-Tea/hexo-circle-of-friends 撞名。

**Comment by linlinzzo** [comment]
> 友链朋友圈这个名字，和 https://github.com/Rock-Candy-Tea/hexo-circle-of-friends 撞名。

友链接力也与开往撞名，不知您有什么建议。

**Comment by MYXXTS** [comment]
友链朋友圈我个人认为不是很有必要。
如果说一定要有一个，那我认为还不如开发一款网页版的rss阅读，后续也可以打包成APP来进行使用

**Comment by linlinzzo** [comment]
将其功能移至 #95 ，将博客文章用一个个“问题”“主题”串起来，找到相似的博客文章。

**Comment by Mabbs** [comment]
iframe可能会相对安全，可以整黑白两套风格

--By Mayx

发件人: ***@***.***>
发送时间: 2022年6月5日 上午 10:33
收件人: ***@***.***>
抄送: ***@***.***>; ***@***.***>
主题: [zh-blogs/blog-daohang] 组内讨论-[友链朋友圈] (Issue #74)


请描述内容内容，并 @ 相关成员
友链接力，我们开发一个 js 放在中文博客网站（不是我们的官网，和网站推荐不一样）上，像谷歌广告那样，当用户访问中文博客时可以看到我们推送的随机博客。


OhYee 2022/5/8 12:44:38
最后这个你是想让别的站点加载这个js么

OhYee 2022/5/8 12:45:35
一方面是作为一个站长，一般是不应该加载第三方js的，存在安全隐患

OhYee 2022/5/8 12:45:59
另一方面是这个js加载之后，要把内容渲染到页面上，很难保证风格统一

OhYee 2022/5/8 12:46:12
基本上不可能做到好看

―

**Comment by OhYee** [comment]
iframe 自适应高度以及和其他站点样式兼容性不太好搞这个不是单纯展示一张图片，对样式侵入性比较强 ---- On 星期二, 11 十月 2022 03:11:46 -0600  ***@***.***  wrote ----
iframe可能会相对安全，可以整黑白两套风格



--By Mayx



发件人: ***@***.***>

发送时间: 2022年6月5日 上午 10:33

收件人: ***@***.***>

抄送: ***@***.***>; ***@***.***>

主题: [zh-blogs/blog-daohang] 组内讨论-[友链朋友圈] (Issue #74)





请描述内容内容，并 @ 相关成员

友链接力，我们开发一个 js 放在中文博客网站（不是我们的官网，和网站推荐不一样）上，像谷歌广告那样，当用户访问中文博客时可以看到我们推送的随机博客。





OhYee 2022/5/8 12:44:38

最后这个你是想让别的站点加载这个js么



OhYee 2022/5/8 12:45:35

一方面是作为一个站长，一般是不应该加载第三方js的，存在安全隐患



OhYee 2022/5/8 12:45:59

另一方面是这个js加载之后，要把内容渲染到页面上，很难保证风格统一



OhYee 2022/5/8 12:46:12

基本上不可能做到好看



―

**Comment by MYXXTS** [comment]
生成不同风格的图片呢？外层再嵌套链接

**Comment by OhYee** [comment]
不同风格怎么定义，有些网站背景不是纯白，颜色不一样会很明显

另外我们这个应该会有比较多的交互能力，单纯图片拼接不太好实现
