### ISSUE TITLE
申请修改信息-[516]

### ISSUE THREAD

**Issue by dengqinzhi** [heyblog/V2#82]
网站序号：516
网站需要修改的信息：
站名    DENG's LIFE
网址    https://deng.life
rss       https://deng.life/feed

ths

**Comment by linlinzzo** [comment]
等会修改。

**Comment by linlinzzo** [comment]
中文博客列表导航 idx 1471，已同步修改。

**Comment by dengqinzhi** [comment]
网站序号：516
网站需要修改的信息：
站名: DENG's LIFE
网址: https://qinzhi.cc/
rss:  https://qinzhi.cc/feed

**Comment by dengqinzhi** [comment]
请帮忙修改下网站信息

**Comment by linlinzzo** [comment]
等会会在列表中修改。

**Comment by dengqinzhi** [comment]
非常感谢！！&nbsp;


24427467
***@***.***



&nbsp;




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2022年11月4日(星期五) 晚上7:08
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [zh-blogs/blog-daohang] 申请修改信息-[516] (Issue #82)





 
等会会在列表中修改。

**Comment by dengqinzhi** [comment]
你好，刚登陆发现网址还没有帮我改，加油




24427467
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zh-blogs/blog-daohang"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月4日(星期五) 晚上7:08
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zh-blogs/blog-daohang] 申请修改信息-[516] (Issue #82)





 
等会会在列表中修改。

**Comment by MYXXTS** [comment]
贵站点在id为1471条，已做修改，且发现您的域名应该有重定向，是否修改？

**Comment by dengqinzhi** [comment]
你好，就是请你帮我改下网站域名
网址：&nbsp; &nbsp; https://qinzhi.cc
rss:&nbsp; &nbsp; &nbsp; &nbsp;https://qinzhi.cc/feed


谢谢


24427467
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zh-blogs/blog-daohang"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月15日(星期二) 下午4:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zh-blogs/blog-daohang] 申请修改信息-[516] (Issue #82)





 
贵站点在id为1471条，已做修改，且发现您的域名应该有重定向，是否修改？

**Comment by dengqinzhi** [comment]
你好，还有那个"开往“的网站也帮我改下域名
ID是516




24427467
***@***.***



&nbsp;





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "zh-blogs/blog-daohang"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2022年11月15日(星期二) 下午4:03
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [zh-blogs/blog-daohang] 申请修改信息-[516] (Issue #82)





 
贵站点在id为1471条，已做修改，且发现您的域名应该有重定向，是否修改？

**Comment by MYXXTS** [comment]
中文博客导航内容已做修改，开往导航内容修改请移步开往仓库按照要求进行修改
