### ISSUE TITLE
请教一下贵项目的标签分类是如何实现的?

### ISSUE THREAD

**Issue by caibingcheng** [heyblog/V2#83]
如题, 请问贵站["标签选择"](https://zhblogs.ohyee.cc/?tab=blog_list&page=1&tags=&search=)一栏中的标签是如何实现的? 是人工分类吗? 还是依赖某分类模型?

我目前在维护一个以独立博客内容为中心的聚合网站[rssblog](https://rssblog.cn/), 期望可以添加文章分类的功能, 但是数据太多, 不适合人工分类, 且尝试过的分词/分类模型, 但是效果不太好. 看了贵站的分类, 效果很好, 期望可以参考一下.

**Comment by soxft** [comment]
目前的确是 `人工分类`

**Comment by linlinzzo** [comment]
人工。AI模型可以讨论一下。

**Comment by linlinzzo** [comment]
@OhYee 是否可以将网站分类反补到文章?

**Comment by redish101** [comment]
本项目目前是人工分类的

发件人: BBing ***@***.***>
日期: 星期四, 2022年6月16日 下午5:49
收件人: zh-blogs/blog-daohang ***@***.***>
抄送: Subscribed ***@***.***>
主题: [zh-blogs/blog-daohang] 请教一下贵项目的标签分类是如何实现的? (Issue #83)

如题, 请问贵站"标签选择"<https://zhblogs.ohyee.cc/?tab=blog_list&page=1&tags=&search=>一栏中的标签是如何实现的? 是人工分类吗? 还是依赖某分类模型?

我目前在维护一个以独立博客内容为中心的聚合网站rssblog<https://rssblog.cn/>, 期望可以添加文章分类的功能, 但是数据太多, 不适合人工分类, 且尝试过的分词/分类模型, 但是效果不太好. 看了贵站的分类, 效果很好, 期望可以参考一下.

―

**Comment by OhYee** [comment]
> @OhYee 是否可以将网站分类反补到文章?

不能，文章内容和博客总体主题可能错很多，可以考虑文章的分类结果生成网站分类

@caibingcheng 
关于文章标签，之前有做过根据统计词频的 demo，不过需要比较大的数据量做语料库，而且效果和人工分类差距很大。
目前我们这边没有相关技术领域的人员，可以考虑合作这部分功能。

**Comment by MYXXTS** [comment]
由于标签分类是由我在负责，所以说一下标签分类：
第一，标签分类在我看来是没有办法自动化分类的，就算是抓取标签也对博客的定义是不准确的。
第二，标签分类在本站是有一套分类标准的，依照此标准可以对博客实现以标签来概括博客的内容。
第三，博客标签标准目前已经有了初步的雏形，后续会以文档的形式发布出来
