### ISSUE TITLE
Bug反馈-[页面未跳转]

### ISSUE THREAD

**Issue by wibus-wee** [heyblog/V2#86]
请仔细描述这个漏洞（浏览器、复现方式等我们需要的信息）：

Safari、Chrome 皆为此问题 因为并不是浏览器的原因

复现方式：详见视频

https://user-images.githubusercontent.com/62133302/174635031-ed76cf77-00c9-4408-9a7e-e030c5739902.mov

**Comment by OhYee** [comment]
复现成功
1. 随机博客推荐切换到博客列表 tab
2. 点击申请加入
3. 点击浏览器后退按钮，不跳转（地址栏更新）

----

猜测原因是 tab 绑定请求参数时未 pushHistory，后续修复

**Comment by wibus-wee** [comment]
另外，在[这个地方](https://github.com/zh-blogs/blog-daohang/blob/a643334a4b10de511b16dc37dc3f8ab0a019920b/utils/index.ts#L206) ，使用的是 `history.replaceState`，个人认为不应该使用`replace` 而使用 `push`
