### ISSUE TITLE
申请修改信息-[221]

### ISSUE THREAD

**Issue by 0xM0on** [heyblog/V2#87]
网站序号：221
网站需要修改的信息：
考完之后荒废太久了……今天维护了一下，更新了一篇内容。
站点的名称和链接都变了，麻烦大佬更新一下。
名称：alpacabro
网址：https://www.alpacabro.com
图标：https://www.alpacabro.com/avater.png
辛苦了~

**Comment by Redish101** [comment]
好的

发件人: alpacabro ***@***.***>
日期: 星期一, 2022年6月20日 下午11:48
收件人: zh-blogs/blog-daohang ***@***.***>
抄送: Subscribed ***@***.***>
主题: [zh-blogs/blog-daohang] 申请修改信息-[221] (Issue #87)

网站序号：221
网站需要修改的信息：
考完之后荒废太久了……今天维护了一下，更新了一篇内容。
站点的名称和链接都变了，麻烦大佬更新一下。
名称：alpacabro
网址：https://www.alpacabro.com
图标：https://www.alpacabro.com/avater.png
辛苦了~

―

**Comment by MYXXTS** [comment]
请添加错误的站点相关信息，方便定位，谢谢。

**Comment by 0xM0on** [comment]
> 请添加错误的站点相关信息，方便定位，谢谢。

不好意思，忘了填写完整了

221 | 侧栏 | alpaca++ | https://www.alpaca.plus


221	侧栏	alpaca++	https://www.alpaca.plus/

**Comment by MYXXTS** [comment]
经查询，未找到贵站点，请于导航列表确认您的错误站点信息，并附以您错误站点信息所在行的截图便于查证。
中文博客导航列表：https://zhblogs.ohyee.cc/

**Comment by linlinzzo** [comment]
zhblogs 里没有。

**Comment by linlinzzo** [comment]
已修改，稍后同步到 main。
