### ISSUE TITLE
组内讨论-[中文独立博客同步到列表]

### ISSUE THREAD

**Issue by linlinzzo** [heyblog/V2#93]
请描述内容内容，并 @ 相关成员
希望在 https://github.com/timqian/chinese-independent-blogs 仓库发生修改时可以推送到这里进行同步。
建议使用 GitHub action 定期（比如每天）抓取仓库里面 csv 查看是否有新增

**Comment by linlinzzo** [comment]
@yzqzss

**Comment by linlinzzo** [comment]
@Mabbs 您能帮忙开发吗？下面是需求：

1. saveweb/rss-list 有新增博客时，可以像 webhook 那样推送到 zh-blogs ，api 文档地址为 https://www.apifox.cn/apidoc/project-1355504/api-31495457 。
2. saveweb/rss-list 有撤下博客时，将 zh-blogs 中的该博客隐藏，等待管理员复审。

Thanks.

**Comment by Mabbs** [comment]
> @Mabbs 您能帮忙开发吗？下面是需求：
> 
> 1. saveweb/rss-list 有新增博客时，可以像 webhook 那样推送到 zh-blogs ，api 文档地址为 https://www.apifox.cn/apidoc/project-1355504/api-31495457 。
> 2. saveweb/rss-list 有撤下博客时，将 zh-blogs 中的该博客隐藏，等待管理员复审。
> 
> Thanks.

OK，我回去看一下
