### ISSUE TITLE
主动提交博客标识

### ISSUE THREAD

**Issue by MYXXTS** [heyblog/V2#94]
为主动提交的博客站点添加一个标识，以及排序，在维护完善信息的时候，我们将优先维护这些主动添加的博客

**Comment by linlinzzo** [comment]
补充一些细节
-----------------------------
后台显示主动提交并可以根据此选项排序就可以
前台不做显示
就是管理员提交的默认非主动提交，用户自己提交的默认是主动提交么

**Comment by MYXXTS** [comment]
然后在此基础之上还需要有一个博客认领功能，将非主动提交博客更改为主动提交的博客

**Comment by linlinzzo** [comment]
> 然后在此基础之上还需要有一个博客认领功能，将非主动提交博客更改为主动提交的博客

那这个可能需要我们也开发一个站长平台，用于认证博客站长。。。

**Comment by MYXXTS** [comment]
暂时不用，因为没有好的解决方案的话可能会导致数据泄露
