### ISSUE TITLE
组内讨论-[中文博客搜索引擎]

### ISSUE THREAD

**Issue by linlinzzo** [heyblog/V2#95]
请描述内容内容，并 @ 相关成员
建立一个索引中文博客博文的搜索引擎。

-------------------------------

建立一个索引“Hexo如何安装？”，添加一些与此相关的博文链接，形成一种“目录”。
当用户输入“Hexo”时，可以跳出“Hexo如何安装？”“Hexo有什么优点？”等目录。

**Comment by imjason** [comment]
可以使用开往爬取的数据

**Comment by linlinzzo** [comment]
> 可以使用开往爬取的数据

简述：开往他们会推送数据给搜索引擎，就像站长在站长平台提交url一样。

**Comment by linlinzzo** [comment]
今天在 https://github.com/zh-blogs/zh-search-engine 用原生 js ”实现“了一下，漏洞百出，摆烂了。 @OhYee
