### ISSUE TITLE
组内讨论-[列表导航数据开放平台]

### ISSUE THREAD

**Issue by linlinzzo** [heyblog/V2#96]
请描述内容内容，并 @ 相关成员
允许已认证的请求通过 get 或 post 申请修改网站信息、获取网站数据。

**Comment by linlinzzo** [comment]
补充：
例如 https://zhblogs.ohyee.cc/api/blogs/random? 就是一个返回随机博客的接口。需要开放的接口还有：

- [ ] 获取指定博客的数据（返回该博客的标签、名称、订阅地址、网站地图）
- [ ] 获取指定标签的博客（目前似乎已实现，但需要写调用文档）

**Comment by linlinzzo** [comment]
补充功能：为 saveweb 开放修改信息接口，例如 saveweb 可以凭借 token 用脚本添加网站的 saveweb-id。
@yzqzss

**Comment by OhYee** [comment]
可以暂时参考

https://github.com/zh-blogs/blog-daohang/blob/main/utils/api.ts

这里是所有接口，而且都有注释

**Comment by linlinzzo** [comment]
https://www.apifox.cn/apidoc/project-1355504/doc-1144392
