### ISSUE TITLE
组内讨论-[新增“镜像网站”]

### ISSUE THREAD

**Issue by linlinzzo** [heyblog/V2#98]
请描述内容内容，并 @ 相关成员
在数据中多存一个“镜像网站”数据，在提交网站查重时多检查一下镜像网站。

注:
1. 已在项目群中讨论。
2. 需要等数据库完成导入后再弄。

**Comment by soxft** [comment]
不建议加入镜像网站, 建议列表中只收集主站点

**Comment by linlinzzo** [comment]
> 不建议加入镜像网站, 建议列表中只收集主站点

此处加入“镜像网站”的目的是去重，暂时不在前台显示。
